<a href="https://colab.research.google.com/github/zacharydayne/Linear-Algebra/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

##Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$A^T = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

In [3]:
A = np.array([
              [1,2,5],
              [4,3,7],
              [8,2,0]
])
A

array([[1, 2, 5],
       [4, 3, 7],
       [8, 2, 0]])

In [4]:
AT1 = np.transpose(A)
AT1

array([[1, 4, 8],
       [2, 3, 2],
       [5, 7, 0]])

In [5]:
AT2 = A.T
AT2

array([[1, 4, 8],
       [2, 3, 2],
       [5, 7, 0]])

In [6]:
np.array_equiv(AT1, AT2)


True

In [8]:
B = np.array ([
               [1,2,3,4],
               [1,0,2,1]
])
B.shape

(2, 4)

In [9]:
np.transpose(B).shape

(4, 2)

In [10]:
B.T.shape

(4, 2)

##Try to create your own matrix(you can try non-squares) to test transposition


In [14]:
C = np.array ([
               [1,4],
               [5,4],
               [9,3],
               [1,3],
               [5,9]
])
C.shape


(5, 2)

In [15]:
np.transpose(C).shape

(2, 5)

In [16]:
C.T.shape

(2, 5)

D = np.

In [22]:
Z = np.array([
              [1,2],
              [3,4]
])
L = np.array([
              [5,6],
              [7,8]
])


In [23]:
np.dot(Z,L)

array([[19, 22],
       [43, 50]])

In [24]:
Z.dot(L)

array([[19, 22],
       [43, 50]])

In [25]:
Z@L

array([[19, 22],
       [43, 50]])

In [26]:
np.matmul(Z,L)

array([[19, 22],
       [43, 50]])

##Rule 1: the inner dimentions of two matrices in question mustbe the same.


In [27]:
E = np. array([
              [2,3],
              [2,4],
              [0,1]
])
F = np. array([
              [3,6],
              [2,4],
              [0,2]
])
G = np. array([
              [1,2,3],
              [2,3,4],
])
print(E.shape)
print(F.shape)
print(G.shape)

(3, 2)
(3, 2)
(2, 3)


In [30]:
E@F

ValueError: ignored

In [31]:
E@G

array([[ 8, 13, 18],
       [10, 16, 22],
       [ 2,  3,  4]])

In [32]:
F@G

array([[15, 24, 33],
       [10, 16, 22],
       [ 4,  6,  8]])

In [33]:
H = np.array ([
               [1,2,3,0],
])
I = np.array ([
               [1,0,4,-1]
])
print(H.shape)
print(I.shape)

(1, 4)
(1, 4)


In [35]:
I.T@H

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [37]:
H@I.T

array([[13]])

##Rule 2: Dot product has special properties

In [44]:
Z = np.array([
              [3,2,1],
              [4,5,1],
              [0,2,1]
])
D = np.array([
              [9,2,6],
              [1,4,0],
              [0,1,0]
])
L = np.array([
           [0,2,6],
           [9,2,1],
           [5,3,8]  
])
print(Z.shape)
print(D.shape)
print(L.shape)

(3, 3)
(3, 3)
(3, 3)


A.B != B.A

In [39]:
Z@L

array([[23, 13, 28],
       [50, 21, 37],
       [23,  7, 10]])

In [40]:
L@Z

array([[ 8, 22,  8],
       [35, 30, 12],
       [27, 41, 16]])

In [55]:
np.array_equiv(Z@L, L@Z)

False

A.(B.C)=(A.B).C

In [42]:
Z@(D@L)

array([[225, 142, 333],
       [381, 212, 467],
       [ 81,  22,  21]])

In [43]:
(Z@D)@L

array([[225, 142, 333],
       [381, 212, 467],
       [ 81,  22,  21]])

In [54]:
np.array_equiv(Z@(D@L), (Z@D)@L)

True

In [53]:
X = np.identity(3)
Z@X

array([[3., 2., 1.],
       [4., 5., 1.],
       [0., 2., 1.]])

In [56]:
Z.dot(X)

array([[3., 2., 1.],
       [4., 5., 1.],
       [0., 2., 1.]])

##Determinant

In [59]:
A = np.array([
              [1,4],
              [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [64]:
B = np.array([
              [1,5,2],
              [3,-1,-1],
              [0,-2,1]
])
np.linalg.det(B)


-30.000000000000014