<a href="https://colab.research.google.com/github/zacharydayne/Linear-Algebra/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Linear Algebra For ECE**
##**Laboratory 4: Matrices**

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##**Matrices**

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.


Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. 
$$


We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

##**Declaring Matrices**


Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.

In [10]:
## Describing matrices: Creating a Function
def describe_mat(matrix):
    print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [14]:
## Declaring a 2 x 2 matrix
A = np.array([
            [1, 2],
            [3, 1]
            ])
describe_mat(A)

matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [15]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [16]:
## Declaring a 3 x 2 matrix
B = np.array([[
              [1, 2],
              [3, 1],
              [5, 7]
              ]])
describe_mat(B)

matrix:
[[[1 2]
  [3 1]
  [5 7]]]

Shape:	(1, 3, 2)
Rank:	3



In [17]:
H = np.array([1,2,3,4,5])
describe_mat(H)

matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



##**Categorizing Matrices**

There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values.** We'll try to go through them.

###**According to Shape**


####**Row and Column Matrices**

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [18]:
## Declaring a Row Matrix

row_mat_1D = np.array([1, 2, 3])
  ## this is a 1-D Matrix with a shape of (3, ), it's not really considered as a row matrix

row_mat_2D = np.array([[1, 2, 3]])
  ## this is a 2-D Matrix with a shape of (1,3)

describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

matrix:
[1 2 3]

Shape:	(3,)
Rank:	1

matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix
col_mat = np.array([
                    [1],
                    [2],
                    [3]
                  ])
  ## this is a 2-D Matrix with a shape of (3,1)    
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [3]]

Shape:	(3, 1)
Rank:	2



####**Square Matrices**

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
##Square Matrix
square_mat = np.array([
                       [1, 2, 5],
                       [6, 2, 8],
                       [9, 1, 4]
])
non_square_mat = np.array([
                           [1, 2, 5],
                           [3, 6, 2]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 2 5]
 [6 2 8]
 [9 1 4]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 6 2]]

Shape:	(2, 3)
Rank:	2
Is Square: False



###**According to Element Values**

####**Null Matrix**

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


####**Zero Matrix**

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1, 2))
zero_mat_sqr = np.zeros((2, 2))
zero_mat_rct = np.zeros((3, 2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####**Ones Matrix**

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
one_mat_row = np.ones((1, 2))
one_mat_sqr = np.ones((2, 2))
one_mat_rct = np.ones((3, 2))

print(f'One Row Matrix: \n{one_mat_row}')
print(f'One Square Matrix: \n{one_mat_sqr}')
print(f'One Rectangular Matrix: \n{one_mat_rct}')

One Row Matrix: 
[[1. 1.]]
One Square Matrix: 
[[1. 1.]
 [1. 1.]]
One Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####**Diagonal Matrix**


A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [20]:
np.array([
          [2,0,0],
          [0,3,0],
          [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [22]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

In [23]:
d = np.diag([2,3,5,7,9,11])
d

array([[ 2,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0, 11]])

####**Identity Matrix**

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

####**Upper Triangular Matrix**

An upper triangular matrix is a matrix that has no values below the diagonal.

In [25]:
A=np.array([
            [1,2,1],
            [0,4,-1],
            [0,0,10]
])
describe_mat(A)

matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2



####**Lower Triangular Matrix**

A lower triangular matrix is a matrix that has no values above the diagonal.

In [27]:
B=np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])
describe_mat(B)

matrix:
[[1 0 0]
 [5 3 0]
 [7 8 5]]

Shape:	(3, 3)
Rank:	2



##

$$
G = \left\{
    \begin{array}\
        x+7x_2+8x_3 \\ 
        2x +2x_2 +2x_3 \\
        4x + 6x_2 +7x_3
    \end{array}
\right. 
$$

##**Practice**

1.) Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$


In [28]:
theta = np.array([
        [5,3,-1]
])
describe_mat(theta)

matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2



2.) Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

3.) 
Given the matrix below, express it as a linear combination in a markdown.


$$ G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix} \\ $$

$$
G = \left\{
    \begin{array}\
        x + 7x_2 + 8x_3 \\
        2x + 2x_2 + 2x_3 \\
        4x + 6x_2 + 7x_3
    \end{array}
\right. \\
$$

##**Matrix Algebra**


####**Addition**

In [29]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [30]:

2+A 
##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

####**Subtraction**

In [31]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [32]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

####**Element-Wise Multiplication**

In [33]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [34]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [36]:
## A@B


In [37]:

alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [38]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

##**Activity**


###**Task 1**

Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

####**Shape, Size and Rank of the Matrix**

In [40]:
def mat_desc(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [42]:
T1 = np.array([
      [6,9,4],
      [2,0,6],
      [6,6,2]
])
mat_desc(T1)

Matrix:
[[6 9 4]
 [2 0 6]
 [6 6 2]]

Shape:	(3, 3)
Rank:	2



![image](https://drive.google.com/file/d/1oH2lL3ncX08orjOqUi7duRqeTMt8isFc/view?usp=sharing)